pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    Python36:
      python.version: '3.6'
    Python27:
      python.version: '2.7'

steps:
  # Set the UsePythonVersion task to reference the matrix variable for its Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
- script: |
    sudo apt-get update && sudo apt-get install -y libsnappy-dev 
  displayName: 'apt update and install'
- script: |
    printenv
    python -m pip install --upgrade pip && pip3 install --upgrade setuptools gnureadline
    pip install -e .
  displayName: 'Upgrade pip and setuptools'
  continueOnError: false
- script: |
    printenv
    pip install tox
    tox -e py -- --junit-xml=testresults.xml
  displayName: 'tox'
- script: |
    curl -fsSL https://testspace-client.s3.amazonaws.com/testspace-linux-dev.tgz | sudo tar -zxvf- -C /usr/local/bin
    testspace config url e18dc52ec2bceda7689d7e5bfed6791e26d449f8:@open.stridespace.com
    testspace [Python-$(python.version)]testresults.xml{test}
  displayName: 'Testspace'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'testresults.xml'
