pool:
  vmImage: 'Ubuntu 16.04'

strategy:
  matrix:
    Python36:
      python.version: '3.6'

steps:
  # Set the UsePythonVersion task to reference the matrix variable for its Python version
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
    architecture: 'x64'
- script: printenv
- script: |
    apt-get update && apt-get install libsnappy-dev
    python -m pip install --upgrade pip && pip3 install --upgrade setuptools gnureadline
    pip install -e .
  displayName: 'Upgrade pip and setuptools'
  continueOnError: false
- script: |
    pip install tox
    tox -e py -- --junit-xml=testresults.xml
  displayName: 'tox'
